### ISSUE TITLE
老版本迁移的一个问题

### ISSUE THREAD

**Issue by luckyyyyy** [zu1k/nali#166]
我是0.x版本过来的，不调试还不知道，被迁移到了
```
ConfigDirPath:/Users/william/Library/Application Support/nali
DataDirPath:/Users/william/Library/Application Support/nali
```

但也把错误的数据库标识迁移过来了
```
cdn-skk-yml
panic: DB format not supported!

goroutine 1 [running]:
github.com/zu1k/nali/internal/db.(*DB).get(0x14000191680)
        /Users/william/nali/internal/db/type.go:55 +0x35c
github.com/zu1k/nali/internal/db.GetDB(0x2)
        /Users/william/nali/internal/db/db.go:55 +0xc0
github.com/zu1k/nali/internal/db.Find(0x1007c99c0?, {0x1400002413e, 0xd})
        /Users/william/nali/internal/db/db.go:76 +0x74
github.com/zu1k/nali/pkg/entity.ParseLine({0x14000024138, 0x14})
        /Users/william/nali/pkg/entity/parse.go:58 +0x7c0
github.com/zu1k/nali/cmd.glob..func2(0x100a8c9c0?, {0x100acaf70, 0x0, 0x0})
        /Users/william/nali/cmd/root.go:76 +0x120
github.com/spf13/cobra.(*Command).execute(0x100a8c9c0, {0x1400010a200, 0x0, 0x0})
        /Users/william/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x100a8c9c0)
        /Users/william/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/william/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/zu1k/nali/cmd.Execute()
        /Users/william/nali/cmd/root.go:86 +0x28
main.main()
        /Users/william/nali/main.go:14 +0x30
```

<img width="679" alt="image" src="https://github.com/zu1k/nali/assets/9210430/1a777511-908c-47fe-97e5-8d4f9fc8b1ab">

**Comment by zu1k** [comment]
哇，版本跨度有点大。建议删除 `/Users/william/Library/Application Support/nali/config.yaml`，然后重新运行 nali 来生成一个新的
