### ISSUE TITLE
SIGSEGV when using geoip database to query ipv6

### ISSUE THREAD

**Issue by huyz-git** [zu1k/nali#43]
```
$ NALI_DB=geoip nali-go
::1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x70091f]

goroutine 1 [running]:
github.com/zu1k/nali/internal/app.ReplaceIPInString(0xc000029e88, 0x3, 0xc000029e88, 0x3)
        github.com/zu1k/nali/internal/app/parse.go:100 +0x67f
github.com/zu1k/nali/internal/app.Root(0xae6098, 0x0, 0x0)
        github.com/zu1k/nali/internal/app/command.go:31 +0xcb
github.com/zu1k/nali/cmd.glob..func3(0xab1aa0, 0xae6098, 0x0, 0x0)
        github.com/zu1k/nali/cmd/root.go:58 +0x51
github.com/spf13/cobra.(*Command).execute(0xab1aa0, 0xc000020210, 0x0, 0x0, 0xab1aa0, 0xc000020210)
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xab1aa0, 0x407de5, 0xc0000261d8, 0x401260)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/zu1k/nali/cmd.Execute()
        github.com/zu1k/nali/cmd/root.go:64 +0x31
main.main()
        github.com/zu1k/nali/main.go:14 +0x2a
```

version 0.2.3

**Comment by zu1k** [comment]
已修复
